"""init migrations

Revision ID: dadc1db062ae
Revises: 
Create Date: 2025-11-09 20:01:07.157377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dadc1db062ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Incident',
    sa.Column('incident_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_message', sa.String(), nullable=True),
    sa.Column('incident_type', sa.Enum('new', 'completed', 'failed', name='incidentstatus'), nullable=True),
    sa.Column('source', sa.Enum('operator', 'monitoring', 'partner', name='incidentsource'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('incident_id', name=op.f('pk_Incident'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Incident')
    # ### end Alembic commands ###
